In [1]:

##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\mathew\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\mathew\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\mathew\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\mathew\anaconda3\envs\myenv\lib\site-packages\tensorflow\pyth

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

In [4]:

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5431, 4418, 1149, 2409], [5431, 4418, 1149, 4386], [5431, 3526, 1149, 5049], [4276, 994, 7407, 3046, 2432], [4276, 994, 7407, 3046, 2122], [2320, 5431, 2386, 1149, 8268], [8777, 1470, 6913, 3046]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5431 4418 1149 2409]
 [   0    0    0    0 5431 4418 1149 4386]
 [   0    0    0    0 5431 3526 1149 5049]
 [   0    0    0 4276  994 7407 3046 2432]
 [   0    0    0 4276  994 7407 3046 2122]
 [   0    0    0 2320 5431 2386 1149 8268]
 [   0    0    0    0 8777 1470 6913 3046]]


In [8]:
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [10]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

[[[-2.78152358e-02  1.83266141e-02 -3.04404851e-02  2.25424767e-03
    5.55926561e-03 -1.18986480e-02  2.43766643e-02  3.97670902e-02
   -1.36581287e-02 -9.60372761e-03]
  [-2.78152358e-02  1.83266141e-02 -3.04404851e-02  2.25424767e-03
    5.55926561e-03 -1.18986480e-02  2.43766643e-02  3.97670902e-02
   -1.36581287e-02 -9.60372761e-03]
  [-2.78152358e-02  1.83266141e-02 -3.04404851e-02  2.25424767e-03
    5.55926561e-03 -1.18986480e-02  2.43766643e-02  3.97670902e-02
   -1.36581287e-02 -9.60372761e-03]
  [-2.78152358e-02  1.83266141e-02 -3.04404851e-02  2.25424767e-03
    5.55926561e-03 -1.18986480e-02  2.43766643e-02  3.97670902e-02
   -1.36581287e-02 -9.60372761e-03]
  [ 9.37180594e-03 -2.02441569e-02 -9.82660055e-03  4.03756611e-02
    2.71828659e-02 -4.66423295e-02 -2.95889266e-02  3.64193954e-02
   -4.94692326e-02  3.91721725e-03]
  [-4.58021872e-02  2.63516344e-02 -3.16985846e-02  4.89365570e-02
   -1.34209022e-02  4.75843288e-02  3.01864035e-02 -4.33440097e-02
    3.09474207e-

In [12]:

embedded_docs[0]

array([   0,    0,    0,    0, 5431, 4418, 1149, 2409])